<?php

namespace App\Enums;

enum Country: string
{
    case AFGHANISTAN = 'AF';
    case ALBANIA = 'AL';
    case AALAND_ISLANDS = 'AX';
    case ALGERIA = 'DZ';
    case AMERICAN_SAMOA = 'AS';
    case ANDORRA = 'AD';
    case ANGOLA = 'AO';
    case ANGUILLA = 'AI';
    case ANTARCTICA = 'AQ';
    case ANTIGUA_AND_BARBUDA = 'AG';
    case ARGENTINA = 'AR';
    case ARMENIA = 'AM';
    case ARUBA = 'AW';
    case AUSTRALIA = 'AU';
    case AUSTRIA = 'AT';
    case AZERBAIJAN = 'AZ';
    case BAHAMAS = 'BS';
    case BAHRAIN = 'BH';
    case BANGLADESH = 'BD';
    case BARBADOS = 'BB';
    case BELARUS = 'BY';
    case BELGIUM = 'BE';
    case BELIZE = 'BZ';
    case BENIN = 'BJ';
    case BERMUDA = 'BM';
    case BHUTAN = 'BT';
    case BOLIVIA = 'BO';
    case BOSNIA_AND_HERZEGOVINA = 'BA';
    case BOTSWANA = 'BW';
    case BOUVET_ISLAND = 'BV';
    case BRAZIL = 'BR';
    case BRITISH_INDIAN_OCEAN_TERRITORY = 'IO';
    case BRUNEI_DARUSSALAM = 'BN';
    case BULGARIA = 'BG';
    case BURKINA_FASO = 'BF';
    case BURUNDI = 'BI';
    case CAMBODIA = 'KH';
    case CAMEROON = 'CM';
    case CANADA = 'CA';
    case CAPE_VERDE = 'CV';
    case CARIBBEAN_NETHERLANDS = 'BQ';
    case CAYMAN_ISLANDS = 'KY';
    case CENTRAL_AFRICAN_REPUBLIC = 'CF';
    case CHAD = 'TD';
    case CHILE = 'CL';
    case CHINA = 'CN';
    case CHRISTMAS_ISLAND = 'CX';
    case COCOS_ISLANDS = 'CC';
    case COLOMBIA = 'CO';
    case COMOROS = 'KM';
    case CONGO = 'CG';
    case CONGO_DR = 'CD';
    case COOK_ISLANDS = 'CK';
    case COSTA_RICA = 'CR';
    case COTE_DIVOIRE = 'CI';
    case CROATIA = 'HR';
    case CUBA = 'CU';
    case CURACAO = 'CW';
    case CYPRUS = 'CY';
    case CZECH_REPUBLIC = 'CZ';
    case DENMARK = 'DK';
    case DJIBOUTI = 'DJ';
    case DOMINICA = 'DM';
    case DOMINICAN_REPUBLIC = 'DO';
    case ECUADOR = 'EC';
    case EGYPT = 'EG';
    case EL_SALVADOR = 'SV';
    case EQUATORIAL_GUINEA = 'GQ';
    case ERITREA = 'ER';
    case ESTONIA = 'EE';
    case ESWATINI = 'SZ';
    case ETHIOPIA = 'ET';
    case FALKLAND_ISLANDS = 'FK';
    case FAROE_ISLANDS = 'FO';
    case FIJI = 'FJ';
    case FINLAND = 'FI';
    case FRANCE = 'FR';
    case FRENCH_GUIANA = 'GF';
    case FRENCH_POLYNESIA = 'PF';
    case FRENCH_SOUTHERN_TERRITORIES = 'TF';
    case GABON = 'GA';
    case GAMBIA = 'GM';
    case GEORGIA = 'GE';
    case GERMANY = 'DE';
    case GHANA = 'GH';
    case GIBRALTAR = 'GI';
    case GREECE = 'GR';
    case GREENLAND = 'GL';
    case GRENADA = 'GD';
    case GUADELOUPE = 'GP';
    case GUAM = 'GU';
    case GUATEMALA = 'GT';
    case GUERNSEY = 'GG';
    case GUINEA = 'GN';
    case GUINEA_BISSAU = 'GW';
    case GUYANA = 'GY';
    case HAITI = 'HT';
    case HEARD_ISLAND_AND_MCDONALD_ISLANDS = 'HM';
    case HOLY_SEE = 'VA';
    case HONDURAS = 'HN';
    case HONG_KONG = 'HK';
    case HUNGARY = 'HU';
    case ICELAND = 'IS';
    case INDIA = 'IN';
    case INDONESIA = 'ID';
    case IRAN = 'IR';
    case IRAQ = 'IQ';
    case IRELAND = 'IE';
    case ISLE_OF_MAN = 'IM';
    case ISRAEL = 'IL';
    case ITALY = 'IT';
    case JAMAICA = 'JM';
    case JAPAN = 'JP';
    case JERSEY = 'JE';
    case JORDAN = 'JO';
    case KAZAKHSTAN = 'KZ';
    case KENYA = 'KE';
    case KIRIBATI = 'KI';
    case KOREA_NORTH = 'KP';
    case KOREA_SOUTH = 'KR';
    case KUWAIT = 'KW';
    case KYRGYZSTAN = 'KG';
    case LAOS = 'LA';
    case LATVIA = 'LV';
    case LEBANON = 'LB';
    case LESOTHO = 'LS';
    case LIBERIA = 'LR';
    case LIBYA = 'LY';
    case LIECHTENSTEIN = 'LI';
    case LITHUANIA = 'LT';
    case LUXEMBOURG = 'LU';
    case MACAO = 'MO';
    case MADAGASCAR = 'MG';
    case MALAWI = 'MW';
    case MALAYSIA = 'MY';
    case MALDIVES = 'MV';
    case MALI = 'ML';
    case MALTA = 'MT';
    case MARSHALL_ISLANDS = 'MH';
    case MARTINIQUE = 'MQ';
    case MAURITANIA = 'MR';
    case MAURITIUS = 'MU';
    case MAYOTTE = 'YT';
    case MEXICO = 'MX';
    case MICRONESIA = 'FM';
    case MOLDOVA = 'MD';
    case MONACO = 'MC';
    case MONGOLIA = 'MN';
    case MONTENEGRO = 'ME';
    case MONTSERRAT = 'MS';
    case MOROCCO = 'MA';
    case MOZAMBIQUE = 'MZ';
    case MYANMAR = 'MM';
    case NAMIBIA = 'NA';
    case NAURU = 'NR';
    case NEPAL = 'NP';
    case NETHERLANDS = 'NL';
    case NEW_CALEDONIA = 'NC';
    case NEW_ZEALAND = 'NZ';
    case NICARAGUA = 'NI';
    case NIGER = 'NE';
    case NIGERIA = 'NG';
    case NIUE = 'NU';
    case NORFOLK_ISLAND = 'NF';
    case NORTH_MACEDONIA = 'MK';
    case NORTHERN_MARIANA_ISLANDS = 'MP';
    case NORWAY = 'NO';
    case OMAN = 'OM';
    case PAKISTAN = 'PK';
    case PALAU = 'PW';
    case PALESTINE = 'PS';
    case PANAMA = 'PA';
    case PAPUA_NEW_GUINEA = 'PG';
    case PARAGUAY = 'PY';
    case PERU = 'PE';
    case PHILIPPINES = 'PH';
    case PITCAIRN = 'PN';
    case POLAND = 'PL';
    case PORTUGAL = 'PT';
    case PUERTO_RICO = 'PR';
    case QATAR = 'QA';
    case REUNION = 'RE';
    case ROMANIA = 'RO';
    case RUSSIAN_FEDERATION = 'RU';
    case RWANDA = 'RW';
    case SAINT_BARTHELEMY = 'BL';
    case SAINT_HELENA = 'SH';
    case SAINT_KITTS_AND_NEVIS = 'KN';
    case SAINT_LUCIA = 'LC';
    case SAINT_MARTIN = 'MF';
    case SAINT_PIERRE_AND_MIQUELON = 'PM';
    case SAINT_VINCENT_AND_THE_GRENADINES = 'VC';
    case SAMOA = 'WS';
    case SAN_MARINO = 'SM';
    case SAO_TOME_AND_PRINCIPE = 'ST';
    case SAUDI_ARABIA = 'SA';
    case SENEGAL = 'SN';
    case SERBIA = 'RS';
    case SEYCHELLES = 'SC';
    case SIERRA_LEONE = 'SL';
    case SINGAPORE = 'SG';
    case SINT_MAARTEN = 'SX';
    case SLOVAKIA = 'SK';
    case SLOVENIA = 'SI';
    case SOLOMON_ISLANDS = 'SB';
    case SOMALIA = 'SO';
    case SOUTH_AFRICA = 'ZA';
    case SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = 'GS';
    case SOUTH_SUDAN = 'SS';
    case SPAIN = 'ES';
    case SRI_LANKA = 'LK';
    case SUDAN = 'SD';
    case SURINAME = 'SR';
    case SVALBARD_AND_JAN_MAYEN = 'SJ';
    case SWEDEN = 'SE';
    case SWITZERLAND = 'CH';
    case SYRIAN_ARAB_REPUBLIC = 'SY';
    case TAIWAN = 'TW';
    case TAJIKISTAN = 'TJ';
    case TANZANIA = 'TZ';
    case THAILAND = 'TH';
    case TIMOR_LESTE = 'TL';
    case TOGO = 'TG';
    case TOKELAU = 'TK';
    case TONGA = 'TO';
    case TRINIDAD_AND_TOBAGO = 'TT';
    case TUNISIA = 'TN';
    case TURKEY = 'TR';
    case TURKMENISTAN = 'TM';
    case TURKS_AND_CAICOS_ISLANDS = 'TC';
    case TUVALU = 'TV';
    case UGANDA = 'UG';
    case UKRAINE = 'UA';
    case UNITED_ARAB_EMIRATES = 'AE';
    case UNITED_KINGDOM = 'GB';
    case UNITED_STATES = 'US';
    case UNITED_STATES_MINOR_OUTLYING_ISLANDS = 'UM';
    case URUGUAY = 'UY';
    case UZBEKISTAN = 'UZ';
    case VANUATU = 'VU';
    case VENEZUELA = 'VE';
    case VIET_NAM = 'VN';
    case VIRGIN_ISLANDS_BRITISH = 'VG';
    case VIRGIN_ISLANDS_US = 'VI';
    case WALLIS_AND_FUTUNA = 'WF';
    case WESTERN_SAHARA = 'EH';
    case YEMEN = 'YE';
    case ZAMBIA = 'ZM';
    case ZIMBABWE = 'ZW';
    case UNKNOWN = 'Unknown';

    public function label()
    {
        return match ($this) {
            static::AFGHANISTAN => 'Afganistán',
            static::ALBANIA => 'Albania',
            static::AALAND_ISLANDS => 'Islas Åland',
            static::ALGERIA => 'Argelia',
            static::AMERICAN_SAMOA => 'Samoa Americana',
            static::ANDORRA => 'Andorra',
            static::ANGOLA => 'Angola',
            static::ANGUILLA => 'Anguila',
            static::ANTARCTICA => 'Antártida',
            static::ANTIGUA_AND_BARBUDA => 'Antigua y Barbuda',
            static::ARGENTINA => 'Argentina',
            static::ARMENIA => 'Armenia',
            static::ARUBA => 'Aruba',
            static::AUSTRALIA => 'Australia',
            static::AUSTRIA => 'Austria',
            static::AZERBAIJAN => 'Azerbaiyán',
            static::BAHAMAS => 'Bahamas',
            static::BAHRAIN => 'Baréin',
            static::BANGLADESH => 'Bangladés',
            static::BARBADOS => 'Barbados',
            static::BELARUS => 'Bielorrusia',
            static::BELGIUM => 'Bélgica',
            static::BELIZE => 'Belice',
            static::BENIN => 'Benín',
            static::BERMUDA => 'Bermudas',
            static::BHUTAN => 'Bután',
            static::BOLIVIA => 'Bolivia',
            static::BOSNIA_AND_HERZEGOVINA => 'Bosnia y Herzegovina',
            static::BOTSWANA => 'Botsuana',
            static::BOUVET_ISLAND => 'Isla Bouvet',
            static::BRAZIL => 'Brasil',
            static::BRITISH_INDIAN_OCEAN_TERRITORY => 'Territorio Británico del Océano Índico',
            static::BRUNEI_DARUSSALAM => 'Brunéi',
            static::BULGARIA => 'Bulgaria',
            static::BURKINA_FASO => 'Burkina Faso',
            static::BURUNDI => 'Burundi',
            static::CAMBODIA => 'Camboya',
            static::CAMEROON => 'Camerún',
            static::CANADA => 'Canadá',
            static::CAPE_VERDE => 'Cabo Verde',
            static::CARIBBEAN_NETHERLANDS => 'Caribe Neerlandés',
            static::CAYMAN_ISLANDS => 'Islas Caimán',
            static::CENTRAL_AFRICAN_REPUBLIC => 'República Centroafricana',
            static::CHAD => 'Chad',
            static::CHILE => 'Chile',
            static::CHINA => 'China',
            static::CHRISTMAS_ISLAND => 'Isla de Navidad',
            static::COCOS_ISLANDS => 'Islas Cocos',
            static::COLOMBIA => 'Colombia',
            static::COMOROS => 'Comoras',
            static::CONGO => 'Congo',
            static::CONGO_DR => 'Congo (Rep. Dem.)',
            static::COOK_ISLANDS => 'Islas Cook',
            static::COSTA_RICA => 'Costa Rica',
            static::COTE_DIVOIRE => 'Costa de Marfil',
            static::CROATIA => 'Croacia',
            static::CUBA => 'Cuba',
            static::CURACAO => 'Curazao',
            static::CYPRUS => 'Chipre',
            static::DENMARK => 'Dinamarca',
            static::DJIBOUTI => 'Yibuti',
            static::DOMINICA => 'Dominica',
            static::DOMINICAN_REPUBLIC => 'República Dominicana',
            static::ECUADOR => 'Ecuador',
            static::EGYPT => 'Egipto',
            static::EL_SALVADOR => 'El Salvador',
            static::EQUATORIAL_GUINEA => 'Guinea Ecuatorial',
            static::ERITREA => 'Eritrea',
            static::ESTONIA => 'Estonia',
            static::ESWATINI => 'Esuatini',
            static::ETHIOPIA => 'Etiopía',
            static::FALKLAND_ISLANDS => 'Islas Malvinas',
            static::FAROE_ISLANDS => 'Islas Feroe',
            static::FIJI => 'Fiyi',
            static::FINLAND => 'Finlandia',
            static::FRANCE => 'Francia',
            static::FRENCH_GUIANA => 'Guayana Francesa',
            static::FRENCH_POLYNESIA => 'Polinesia Francesa',
            static::FRENCH_SOUTHERN_TERRITORIES => 'Territorios Australes Franceses',
            static::GABON => 'Gabón',
            static::GAMBIA => 'Gambia',
            static::GEORGIA => 'Georgia',
            static::GERMANY => 'Alemania',
            static::GHANA => 'Ghana',
            static::GIBRALTAR => 'Gibraltar',
            static::GREECE => 'Grecia',
            static::GREENLAND => 'Groenlandia',
            static::GRENADA => 'Granada',
            static::GUADELOUPE => 'Guadalupe',
            static::GUAM => 'Guam',
            static::GUATEMALA => 'Guatemala',
            static::GUERNSEY => 'Guernsey',
            static::GUINEA => 'Guinea',
            static::GUINEA_BISSAU => 'Guinea-Bisáu',
            static::GUYANA => 'Guyana',
            static::HAITI => 'Haití',
            static::HEARD_ISLAND_AND_MCDONALD_ISLANDS => 'Islas Heard y McDonald',
            static::HOLY_SEE => 'Santa Sede',
            static::HONDURAS => 'Honduras',
            static::HONG_KONG => 'Hong Kong',
            static::HUNGARY => 'Hungría',
            static::ICELAND => 'Islandia',
            static::INDIA => 'India',
            static::INDONESIA => 'Indonesia',
            static::IRAN => 'Irán',
            static::IRAQ => 'Irak',
            static::IRELAND => 'Irlanda',
            static::ISLE_OF_MAN => 'Isla de Man',
            static::ISRAEL => 'Israel',
            static::ITALY => 'Italia',
            static::JAMAICA => 'Jamaica',
            static::JAPAN => 'Japón',
            static::JERSEY => 'Jersey',
            static::JORDAN => 'Jordania',
            static::KAZAKHSTAN => 'Kazajistán',
            static::KENYA => 'Kenia',
            static::KIRIBATI => 'Kiribati',
            static::KOREA_NORTH => 'Corea del Norte',
            static::KOREA_SOUTH => 'Corea del Sur',
            static::KUWAIT => 'Kuwait',
            static::KYRGYZSTAN => 'Kirguistán',
            static::LAOS => 'Laos',
            static::LATVIA => 'Letonia',
            static::LEBANON => 'Líbano',
            static::LESOTHO => 'Lesoto',
            static::LIBERIA => 'Liberia',
            static::LIBYA => 'Libia',
            static::LIECHTENSTEIN => 'Liechtenstein',
            static::LITHUANIA => 'Lituania',
            static::LUXEMBOURG => 'Luxemburgo',
            static::MACAO => 'Macao',
            static::MADAGASCAR => 'Madagascar',
            static::MALAWI => 'Malaui',
            static::MALAYSIA => 'Malasia',
            static::MALDIVES => 'Maldivas',
            static::MALI => 'Mali',
            static::MALTA => 'Malta',
            static::MARSHALL_ISLANDS => 'Islas Marshall',
            static::MARTINIQUE => 'Martinica',
            static::MAURITANIA => 'Mauritania',
            static::MAURITIUS => 'Mauricio',
            static::MAYOTTE => 'Mayotte',
            static::MEXICO => 'México',
            static::MICRONESIA => 'Micronesia',
            static::MOLDOVA => 'Moldavia',
            static::MONACO => 'Mónaco',
            static::MONGOLIA => 'Mongolia',
            static::MONTENEGRO => 'Montenegro',
            static::MONTSERRAT => 'Montserrat',
            static::MOROCCO => 'Marruecos',
            static::MOZAMBIQUE => 'Mozambique',
            static::MYANMAR => 'Myanmar',
            static::NAMIBIA => 'Namibia',
            static::NAURU => 'Nauru',
            static::NEPAL => 'Nepal',
            static::NETHERLANDS => 'Países Bajos',
            static::NEW_CALEDONIA => 'Nueva Caledonia',
            static::NEW_ZEALAND => 'Nueva Zelanda',
            static::NICARAGUA => 'Nicaragua',
            static::NIGER => 'Níger',
            static::NIGERIA => 'Nigeria',
            static::NIUE => 'Niue',
            static::NORFOLK_ISLAND => 'Isla Norfolk',
            static::NORTH_MACEDONIA => 'Macedonia del Norte',
            static::NORTHERN_MARIANA_ISLANDS => 'Islas Marianas del Norte',
            static::NORWAY => 'Noruega',
            static::OMAN => 'Omán',
            static::PAKISTAN => 'Pakistán',
            static::PALAU => 'Palaos',
            static::PALESTINE => 'Palestina',
            static::PANAMA => 'Panamá',
            static::PAPUA_NEW_GUINEA => 'Papúa Nueva Guinea',
            static::PARAGUAY => 'Paraguay',
            static::PERU => 'Perú',
            static::PHILIPPINES => 'Filipinas',
            static::PITCAIRN => 'Islas Pitcairn',
            static::POLAND => 'Polonia',
            static::PORTUGAL => 'Portugal',
            static::PUERTO_RICO => 'Puerto Rico',
            static::QATAR => 'Catar',
            static::REUNION => 'Reunión',
            static::ROMANIA => 'Rumanía',
            static::RUSSIAN_FEDERATION => 'Rusia',
            static::RWANDA => 'Ruanda',
            static::SAINT_BARTHELEMY => 'San Bartolomé',
            static::SAINT_HELENA => 'Santa Elena',
            static::SAINT_KITTS_AND_NEVIS => 'San Cristóbal y Nieves',
            static::SAINT_LUCIA => 'Santa Lucía',
            static::SAINT_MARTIN => 'San Martín',
            static::SAINT_PIERRE_AND_MIQUELON => 'San Pedro y Miquelón',
            static::SAINT_VINCENT_AND_THE_GRENADINES => 'San Vicente y las Granadinas',
            static::SAMOA => 'Samoa',
            static::SAN_MARINO => 'San Marino',
            static::SAO_TOME_AND_PRINCIPE => 'Santo Tomé y Príncipe',
            static::SAUDI_ARABIA => 'Arabia Saudita',
            static::SENEGAL => 'Senegal',
            static::SERBIA => 'Serbia',
            static::SEYCHELLES => 'Seychelles',
            static::SIERRA_LEONE => 'Sierra Leona',
            static::SINGAPORE => 'Singapur',
            static::SINT_MAARTEN => 'Sint Maarten',
            static::SLOVAKIA => 'Eslovaquia',
            static::SLOVENIA => 'Eslovenia',
            static::SOLOMON_ISLANDS => 'Islas Salomón',
            static::SOMALIA => 'Somalia',
            static::SOUTH_AFRICA => 'Sudáfrica',
            static::SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS => 'Islas Georgia del Sur y Sandwich del Sur',
            static::SOUTH_SUDAN => 'Sudán del Sur',
            static::SPAIN => 'España',
            static::SRI_LANKA => 'Sri Lanka',
            static::SUDAN => 'Sudán',
            static::SURINAME => 'Surinam',
            static::SVALBARD_AND_JAN_MAYEN => 'Svalbard y Jan Mayen',
            static::SWEDEN => 'Suecia',
            static::SWITZERLAND => 'Suiza',
            static::SYRIAN_ARAB_REPUBLIC => 'República Árabe Siria',
            static::TAIWAN => 'Taiwán',
            static::TAJIKISTAN => 'Tayikistán',
            static::TANZANIA => 'Tanzania',
            static::THAILAND => 'Tailandia',
            static::TIMOR_LESTE => 'Timor-Leste',
            static::TOGO => 'Togo',
            static::TOKELAU => 'Tokelau',
            static::TONGA => 'Tonga',
            static::TRINIDAD_AND_TOBAGO => 'Trinidad y Tobago',
            static::TUNISIA => 'Túnez',
            static::TURKEY => 'Turquía',
            static::TURKMENISTAN => 'Turkmenistán',
            static::TURKS_AND_CAICOS_ISLANDS => 'Islas Turcas y Caicos',
            static::TUVALU => 'Tuvalu',
            static::UGANDA => 'Uganda',
            static::UKRAINE => 'Ucrania',
            static::UNITED_ARAB_EMIRATES => 'Emiratos Árabes Unidos',
            static::UNITED_KINGDOM => 'Reino Unido',
            static::UNITED_STATES => 'Estados Unidos',
            static::UNITED_STATES_MINOR_OUTLYING_ISLANDS => 'Islas Ultramarinas Menores de Estados Unidos',
            static::URUGUAY => 'Uruguay',
            static::UZBEKISTAN => 'Uzbekistán',
            static::VANUATU => 'Vanuatu',
            static::VENEZUELA => 'Venezuela',
            static::VIET_NAM => 'Vietnam',
            static::VIRGIN_ISLANDS_BRITISH => 'Islas Vírgenes Británicas',
            static::VIRGIN_ISLANDS_US => 'Islas Vírgenes de los Estados Unidos',
            static::WALLIS_AND_FUTUNA => 'Wallis y Futuna',
            static::WESTERN_SAHARA => 'Sahara Occidental',
            static::YEMEN => 'Yemen',
            static::ZAMBIA => 'Zambia',
            static::ZIMBABWE => 'Zimbabue',
            static::UNKNOWN => 'Desconocido',
        };
    }
}
