<?php

namespace App\Enums;

enum Country: string
{
    case AFGHANISTAN = 'AF';
    case ALBANIA = 'AL';
    case AALAND_ISLANDS = 'AX';
    case ALGERIA = 'DZ';
    case AMERICAN_SAMOA = 'AS';
    case ANDORRA = 'AD';
    case ANGOLA = 'AO';
    case ANGUILLA = 'AI';
    case ANTARCTICA = 'AQ';
    case ANTIGUA_AND_BARBUDA = 'AG';
    case ARGENTINA = 'AR';
    case ARMENIA = 'AM';
    case ARUBA = 'AW';
    case AUSTRALIA = 'AU';
    case AUSTRIA = 'AT';
    case AZERBAIJAN = 'AZ';
    case BAHAMAS = 'BS';
    case BAHRAIN = 'BH';
    case BANGLADESH = 'BD';
    case BARBADOS = 'BB';
    case BELARUS = 'BY';
    case BELGIUM = 'BE';
    case BELIZE = 'BZ';
    case BENIN = 'BJ';
    case BERMUDA = 'BM';
    case BHUTAN = 'BT';
    case BOLIVIA = 'BO';
    case BOSNIA_AND_HERZEGOVINA = 'BA';
    case BOTSWANA = 'BW';
    case BOUVET_ISLAND = 'BV';
    case BRAZIL = 'BR';
    case BRITISH_INDIAN_OCEAN_TERRITORY = 'IO';
    case BRUNEI_DARUSSALAM = 'BN';
    case BULGARIA = 'BG';
    case BURKINA_FASO = 'BF';
    case BURUNDI = 'BI';
    case CAMBODIA = 'KH';
    case CAMEROON = 'CM';
    case CANADA = 'CA';
    case CAPE_VERDE = 'CV';
    case CARIBBEAN_NETHERLANDS = 'BQ';
    case CAYMAN_ISLANDS = 'KY';
    case CENTRAL_AFRICAN_REPUBLIC = 'CF';
    case CHAD = 'TD';
    case CHILE = 'CL';
    case CHINA = 'CN';
    case CHRISTMAS_ISLAND = 'CX';
    case COCOS_ISLANDS = 'CC';
    case COLOMBIA = 'CO';
    case COMOROS = 'KM';
    case CONGO = 'CG';
    case CONGO_DR = 'CD';
    case COOK_ISLANDS = 'CK';
    case COSTA_RICA = 'CR';
    case COTE_DIVOIRE = 'CI';
    case CROATIA = 'HR';
    case CUBA = 'CU';
    case CURACAO = 'CW';
    case CYPRUS = 'CY';
    case CZECH_REPUBLIC = 'CZ';
    case DENMARK = 'DK';
    case DJIBOUTI = 'DJ';
    case DOMINICA = 'DM';
    case DOMINICAN_REPUBLIC = 'DO';
    case ECUADOR = 'EC';
    case EGYPT = 'EG';
    case EL_SALVADOR = 'SV';
    case EQUATORIAL_GUINEA = 'GQ';
    case ERITREA = 'ER';
    case ESTONIA = 'EE';
    case ESWATINI = 'SZ';
    case ETHIOPIA = 'ET';
    case FALKLAND_ISLANDS = 'FK';
    case FAROE_ISLANDS = 'FO';
    case FIJI = 'FJ';
    case FINLAND = 'FI';
    case FRANCE = 'FR';
    case FRENCH_GUIANA = 'GF';
    case FRENCH_POLYNESIA = 'PF';
    case FRENCH_SOUTHERN_TERRITORIES = 'TF';
    case GABON = 'GA';
    case GAMBIA = 'GM';
    case GEORGIA = 'GE';
    case GERMANY = 'DE';
    case GHANA = 'GH';
    case GIBRALTAR = 'GI';
    case GREECE = 'GR';
    case GREENLAND = 'GL';
    case GRENADA = 'GD';
    case GUADELOUPE = 'GP';
    case GUAM = 'GU';
    case GUATEMALA = 'GT';
    case GUERNSEY = 'GG';
    case GUINEA = 'GN';
    case GUINEA_BISSAU = 'GW';
    case GUYANA = 'GY';
    case HAITI = 'HT';
    case HEARD_ISLAND_AND_MCDONALD_ISLANDS = 'HM';
    case HOLY_SEE = 'VA';
    case HONDURAS = 'HN';
    case HONG_KONG = 'HK';
    case HUNGARY = 'HU';
    case ICELAND = 'IS';
    case INDIA = 'IN';
    case INDONESIA = 'ID';
    case IRAN = 'IR';
    case IRAQ = 'IQ';
    case IRELAND = 'IE';
    case ISLE_OF_MAN = 'IM';
    case ISRAEL = 'IL';
    case ITALY = 'IT';
    case JAMAICA = 'JM';
    case JAPAN = 'JP';
    case JERSEY = 'JE';
    case JORDAN = 'JO';
    case KAZAKHSTAN = 'KZ';
    case KENYA = 'KE';
    case KIRIBATI = 'KI';
    case KOREA_NORTH = 'KP';
    case KOREA_SOUTH = 'KR';
    case KUWAIT = 'KW';
    case KYRGYZSTAN = 'KG';
    case LAOS = 'LA';
    case LATVIA = 'LV';
    case LEBANON = 'LB';
    case LESOTHO = 'LS';
    case LIBERIA = 'LR';
    case LIBYA = 'LY';
    case LIECHTENSTEIN = 'LI';
    case LITHUANIA = 'LT';
    case LUXEMBOURG = 'LU';
    case MACAO = 'MO';
    case MADAGASCAR = 'MG';
    case MALAWI = 'MW';
    case MALAYSIA = 'MY';
    case MALDIVES = 'MV';
    case MALI = 'ML';
    case MALTA = 'MT';
    case MARSHALL_ISLANDS = 'MH';
    case MARTINIQUE = 'MQ';
    case MAURITANIA = 'MR';
    case MAURITIUS = 'MU';
    case MAYOTTE = 'YT';
    case MEXICO = 'MX';
    case MICRONESIA = 'FM';
    case MOLDOVA = 'MD';
    case MONACO = 'MC';
    case MONGOLIA = 'MN';
    case MONTENEGRO = 'ME';
    case MONTSERRAT = 'MS';
    case MOROCCO = 'MA';
    case MOZAMBIQUE = 'MZ';
    case MYANMAR = 'MM';
    case NAMIBIA = 'NA';
    case NAURU = 'NR';
    case NEPAL = 'NP';
    case NETHERLANDS = 'NL';
    case NEW_CALEDONIA = 'NC';
    case NEW_ZEALAND = 'NZ';
    case NICARAGUA = 'NI';
    case NIGER = 'NE';
    case NIGERIA = 'NG';
    case NIUE = 'NU';
    case NORFOLK_ISLAND = 'NF';
    case NORTH_MACEDONIA = 'MK';
    case NORTHERN_MARIANA_ISLANDS = 'MP';
    case NORWAY = 'NO';
    case OMAN = 'OM';
    case PAKISTAN = 'PK';
    case PALAU = 'PW';
    case PALESTINE = 'PS';
    case PANAMA = 'PA';
    case PAPUA_NEW_GUINEA = 'PG';
    case PARAGUAY = 'PY';
    case PERU = 'PE';
    case PHILIPPINES = 'PH';
    case PITCAIRN = 'PN';
    case POLAND = 'PL';
    case PORTUGAL = 'PT';
    case PUERTO_RICO = 'PR';
    case QATAR = 'QA';
    case REUNION = 'RE';
    case ROMANIA = 'RO';
    case RUSSIAN_FEDERATION = 'RU';
    case RWANDA = 'RW';
    case SAINT_BARTHELEMY = 'BL';
    case SAINT_HELENA = 'SH';
    case SAINT_KITTS_AND_NEVIS = 'KN';
    case SAINT_LUCIA = 'LC';
    case SAINT_MARTIN = 'MF';
    case SAINT_PIERRE_AND_MIQUELON = 'PM';
    case SAINT_VINCENT_AND_THE_GRENADINES = 'VC';
    case SAMOA = 'WS';
    case SAN_MARINO = 'SM';
    case SAO_TOME_AND_PRINCIPE = 'ST';
    case SAUDI_ARABIA = 'SA';
    case SENEGAL = 'SN';
    case SERBIA = 'RS';
    case SEYCHELLES = 'SC';
    case SIERRA_LEONE = 'SL';
    case SINGAPORE = 'SG';
    case SINT_MAARTEN = 'SX';
    case SLOVAKIA = 'SK';
    case SLOVENIA = 'SI';
    case SOLOMON_ISLANDS = 'SB';
    case SOMALIA = 'SO';
    case SOUTH_AFRICA = 'ZA';
    case SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = 'GS';
    case SOUTH_SUDAN = 'SS';
    case SPAIN = 'ES';
    case SRI_LANKA = 'LK';
    case SUDAN = 'SD';
    case SURINAME = 'SR';
    case SVALBARD_AND_JAN_MAYEN = 'SJ';
    case SWEDEN = 'SE';
    case SWITZERLAND = 'CH';
    case SYRIAN_ARAB_REPUBLIC = 'SY';
    case TAIWAN = 'TW';
    case TAJIKISTAN = 'TJ';
    case TANZANIA = 'TZ';
    case THAILAND = 'TH';
    case TIMOR_LESTE = 'TL';
    case TOGO = 'TG';
    case TOKELAU = 'TK';
    case TONGA = 'TO';
    case TRINIDAD_AND_TOBAGO = 'TT';
    case TUNISIA = 'TN';
    case TURKEY = 'TR';
    case TURKMENISTAN = 'TM';
    case TURKS_AND_CAICOS_ISLANDS = 'TC';
    case TUVALU = 'TV';
    case UGANDA = 'UG';
    case UKRAINE = 'UA';
    case UNITED_ARAB_EMIRATES = 'AE';
    case UNITED_KINGDOM = 'GB';
    case UNITED_STATES = 'US';
    case UNITED_STATES_MINOR_OUTLYING_ISLANDS = 'UM';
    case URUGUAY = 'UY';
    case UZBEKISTAN = 'UZ';
    case VANUATU = 'VU';
    case VENEZUELA = 'VE';
    case VIET_NAM = 'VN';
    case VIRGIN_ISLANDS_BRITISH = 'VG';
    case VIRGIN_ISLANDS_US = 'VI';
    case WALLIS_AND_FUTUNA = 'WF';
    case WESTERN_SAHARA = 'EH';
    case YEMEN = 'YE';
    case ZAMBIA = 'ZM';
    case ZIMBABWE = 'ZW';
    case UNKNOWN = 'Unknown';

    public function label()
    {
        return match ($this) {
            self::AFGHANISTAN => 'Afganistán',
            self::ALBANIA => 'Albania',
            self::AALAND_ISLANDS => 'Islas Åland',
            self::ALGERIA => 'Argelia',
            self::AMERICAN_SAMOA => 'Samoa Americana',
            self::ANDORRA => 'Andorra',
            self::ANGOLA => 'Angola',
            self::ANGUILLA => 'Anguila',
            self::ANTARCTICA => 'Antártida',
            self::ANTIGUA_AND_BARBUDA => 'Antigua y Barbuda',
            self::ARGENTINA => 'Argentina',
            self::ARMENIA => 'Armenia',
            self::ARUBA => 'Aruba',
            self::AUSTRALIA => 'Australia',
            self::AUSTRIA => 'Austria',
            self::AZERBAIJAN => 'Azerbaiyán',
            self::BAHAMAS => 'Bahamas',
            self::BAHRAIN => 'Baréin',
            self::BANGLADESH => 'Bangladés',
            self::BARBADOS => 'Barbados',
            self::BELARUS => 'Bielorrusia',
            self::BELGIUM => 'Bélgica',
            self::BELIZE => 'Belice',
            self::BENIN => 'Benín',
            self::BERMUDA => 'Bermudas',
            self::BHUTAN => 'Bután',
            self::BOLIVIA => 'Bolivia',
            self::BOSNIA_AND_HERZEGOVINA => 'Bosnia y Herzegovina',
            self::BOTSWANA => 'Botsuana',
            self::BOUVET_ISLAND => 'Isla Bouvet',
            self::BRAZIL => 'Brasil',
            self::BRITISH_INDIAN_OCEAN_TERRITORY => 'Territorio Británico del Océano Índico',
            self::BRUNEI_DARUSSALAM => 'Brunéi',
            self::BULGARIA => 'Bulgaria',
            self::BURKINA_FASO => 'Burkina Faso',
            self::BURUNDI => 'Burundi',
            self::CAMBODIA => 'Camboya',
            self::CAMEROON => 'Camerún',
            self::CANADA => 'Canadá',
            self::CAPE_VERDE => 'Cabo Verde',
            self::CARIBBEAN_NETHERLANDS => 'Caribe Neerlandés',
            self::CAYMAN_ISLANDS => 'Islas Caimán',
            self::CENTRAL_AFRICAN_REPUBLIC => 'República Centroafricana',
            self::CHAD => 'Chad',
            self::CHILE => 'Chile',
            self::CHINA => 'China',
            self::CHRISTMAS_ISLAND => 'Isla de Navidad',
            self::COCOS_ISLANDS => 'Islas Cocos',
            self::COLOMBIA => 'Colombia',
            self::COMOROS => 'Comoras',
            self::CONGO => 'Congo',
            self::CONGO_DR => 'Congo (Rep. Dem.)',
            self::COOK_ISLANDS => 'Islas Cook',
            self::COSTA_RICA => 'Costa Rica',
            self::COTE_DIVOIRE => 'Costa de Marfil',
            self::CROATIA => 'Croacia',
            self::CUBA => 'Cuba',
            self::CURACAO => 'Curazao',
            self::CYPRUS => 'Chipre',
            self::DENMARK => 'Dinamarca',
            self::DJIBOUTI => 'Yibuti',
            self::DOMINICA => 'Dominica',
            self::DOMINICAN_REPUBLIC => 'República Dominicana',
            self::ECUADOR => 'Ecuador',
            self::EGYPT => 'Egipto',
            self::EL_SALVADOR => 'El Salvador',
            self::EQUATORIAL_GUINEA => 'Guinea Ecuatorial',
            self::ERITREA => 'Eritrea',
            self::ESTONIA => 'Estonia',
            self::ESWATINI => 'Esuatini',
            self::ETHIOPIA => 'Etiopía',
            self::FALKLAND_ISLANDS => 'Islas Malvinas',
            self::FAROE_ISLANDS => 'Islas Feroe',
            self::FIJI => 'Fiyi',
            self::FINLAND => 'Finlandia',
            self::FRANCE => 'Francia',
            self::FRENCH_GUIANA => 'Guayana Francesa',
            self::FRENCH_POLYNESIA => 'Polinesia Francesa',
            self::FRENCH_SOUTHERN_TERRITORIES => 'Territorios Australes Franceses',
            self::GABON => 'Gabón',
            self::GAMBIA => 'Gambia',
            self::GEORGIA => 'Georgia',
            self::GERMANY => 'Alemania',
            self::GHANA => 'Ghana',
            self::GIBRALTAR => 'Gibraltar',
            self::GREECE => 'Grecia',
            self::GREENLAND => 'Groenlandia',
            self::GRENADA => 'Granada',
            self::GUADELOUPE => 'Guadalupe',
            self::GUAM => 'Guam',
            self::GUATEMALA => 'Guatemala',
            self::GUERNSEY => 'Guernsey',
            self::GUINEA => 'Guinea',
            self::GUINEA_BISSAU => 'Guinea-Bisáu',
            self::GUYANA => 'Guyana',
            self::HAITI => 'Haití',
            self::HEARD_ISLAND_AND_MCDONALD_ISLANDS => 'Islas Heard y McDonald',
            self::HOLY_SEE => 'Santa Sede',
            self::HONDURAS => 'Honduras',
            self::HONG_KONG => 'Hong Kong',
            self::HUNGARY => 'Hungría',
            self::ICELAND => 'Islandia',
            self::INDIA => 'India',
            self::INDONESIA => 'Indonesia',
            self::IRAN => 'Irán',
            self::IRAQ => 'Irak',
            self::IRELAND => 'Irlanda',
            self::ISLE_OF_MAN => 'Isla de Man',
            self::ISRAEL => 'Israel',
            self::ITALY => 'Italia',
            self::JAMAICA => 'Jamaica',
            self::JAPAN => 'Japón',
            self::JERSEY => 'Jersey',
            self::JORDAN => 'Jordania',
            self::KAZAKHSTAN => 'Kazajistán',
            self::KENYA => 'Kenia',
            self::KIRIBATI => 'Kiribati',
            self::KOREA_NORTH => 'Corea del Norte',
            self::KOREA_SOUTH => 'Corea del Sur',
            self::KUWAIT => 'Kuwait',
            self::KYRGYZSTAN => 'Kirguistán',
            self::LAOS => 'Laos',
            self::LATVIA => 'Letonia',
            self::LEBANON => 'Líbano',
            self::LESOTHO => 'Lesoto',
            self::LIBERIA => 'Liberia',
            self::LIBYA => 'Libia',
            self::LIECHTENSTEIN => 'Liechtenstein',
            self::LITHUANIA => 'Lituania',
            self::LUXEMBOURG => 'Luxemburgo',
            self::MACAO => 'Macao',
            self::MADAGASCAR => 'Madagascar',
            self::MALAWI => 'Malaui',
            self::MALAYSIA => 'Malasia',
            self::MALDIVES => 'Maldivas',
            self::MALI => 'Mali',
            self::MALTA => 'Malta',
            self::MARSHALL_ISLANDS => 'Islas Marshall',
            self::MARTINIQUE => 'Martinica',
            self::MAURITANIA => 'Mauritania',
            self::MAURITIUS => 'Mauricio',
            self::MAYOTTE => 'Mayotte',
            self::MEXICO => 'México',
            self::MICRONESIA => 'Micronesia',
            self::MOLDOVA => 'Moldavia',
            self::MONACO => 'Mónaco',
            self::MONGOLIA => 'Mongolia',
            self::MONTENEGRO => 'Montenegro',
            self::MONTSERRAT => 'Montserrat',
            self::MOROCCO => 'Marruecos',
            self::MOZAMBIQUE => 'Mozambique',
            self::MYANMAR => 'Myanmar',
            self::NAMIBIA => 'Namibia',
            self::NAURU => 'Nauru',
            self::NEPAL => 'Nepal',
            self::NETHERLANDS => 'Países Bajos',
            self::NEW_CALEDONIA => 'Nueva Caledonia',
            self::NEW_ZEALAND => 'Nueva Zelanda',
            self::NICARAGUA => 'Nicaragua',
            self::NIGER => 'Níger',
            self::NIGERIA => 'Nigeria',
            self::NIUE => 'Niue',
            self::NORFOLK_ISLAND => 'Isla Norfolk',
            self::NORTH_MACEDONIA => 'Macedonia del Norte',
            self::NORTHERN_MARIANA_ISLANDS => 'Islas Marianas del Norte',
            self::NORWAY => 'Noruega',
            self::OMAN => 'Omán',
            self::PAKISTAN => 'Pakistán',
            self::PALAU => 'Palaos',
            self::PALESTINE => 'Palestina',
            self::PANAMA => 'Panamá',
            self::PAPUA_NEW_GUINEA => 'Papúa Nueva Guinea',
            self::PARAGUAY => 'Paraguay',
            self::PERU => 'Perú',
            self::PHILIPPINES => 'Filipinas',
            self::PITCAIRN => 'Islas Pitcairn',
            self::POLAND => 'Polonia',
            self::PORTUGAL => 'Portugal',
            self::PUERTO_RICO => 'Puerto Rico',
            self::QATAR => 'Catar',
            self::REUNION => 'Reunión',
            self::ROMANIA => 'Rumanía',
            self::RUSSIAN_FEDERATION => 'Rusia',
            self::RWANDA => 'Ruanda',
            self::SAINT_BARTHELEMY => 'San Bartolomé',
            self::SAINT_HELENA => 'Santa Elena',
            self::SAINT_KITTS_AND_NEVIS => 'San Cristóbal y Nieves',
            self::SAINT_LUCIA => 'Santa Lucía',
            self::SAINT_MARTIN => 'San Martín',
            self::SAINT_PIERRE_AND_MIQUELON => 'San Pedro y Miquelón',
            self::SAINT_VINCENT_AND_THE_GRENADINES => 'San Vicente y las Granadinas',
            self::SAMOA => 'Samoa',
            self::SAN_MARINO => 'San Marino',
            self::SAO_TOME_AND_PRINCIPE => 'Santo Tomé y Príncipe',
            self::SAUDI_ARABIA => 'Arabia Saudita',
            self::SENEGAL => 'Senegal',
            self::SERBIA => 'Serbia',
            self::SEYCHELLES => 'Seychelles',
            self::SIERRA_LEONE => 'Sierra Leona',
            self::SINGAPORE => 'Singapur',
            self::SINT_MAARTEN => 'Sint Maarten',
            self::SLOVAKIA => 'Eslovaquia',
            self::SLOVENIA => 'Eslovenia',
            self::SOLOMON_ISLANDS => 'Islas Salomón',
            self::SOMALIA => 'Somalia',
            self::SOUTH_AFRICA => 'Sudáfrica',
            self::SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS => 'Islas Georgia del Sur y Sandwich del Sur',
            self::SOUTH_SUDAN => 'Sudán del Sur',
            self::SPAIN => 'España',
            self::SRI_LANKA => 'Sri Lanka',
            self::SUDAN => 'Sudán',
            self::SURINAME => 'Surinam',
            self::SVALBARD_AND_JAN_MAYEN => 'Svalbard y Jan Mayen',
            self::SWEDEN => 'Suecia',
            self::SWITZERLAND => 'Suiza',
            self::SYRIAN_ARAB_REPUBLIC => 'República Árabe Siria',
            self::TAIWAN => 'Taiwán',
            self::TAJIKISTAN => 'Tayikistán',
            self::TANZANIA => 'Tanzania',
            self::THAILAND => 'Tailandia',
            self::TIMOR_LESTE => 'Timor-Leste',
            self::TOGO => 'Togo',
            self::TOKELAU => 'Tokelau',
            self::TONGA => 'Tonga',
            self::TRINIDAD_AND_TOBAGO => 'Trinidad y Tobago',
            self::TUNISIA => 'Túnez',
            self::TURKEY => 'Turquía',
            self::TURKMENISTAN => 'Turkmenistán',
            self::TURKS_AND_CAICOS_ISLANDS => 'Islas Turcas y Caicos',
            self::TUVALU => 'Tuvalu',
            self::UGANDA => 'Uganda',
            self::UKRAINE => 'Ucrania',
            self::UNITED_ARAB_EMIRATES => 'Emiratos Árabes Unidos',
            self::UNITED_KINGDOM => 'Reino Unido',
            self::UNITED_STATES => 'Estados Unidos',
            self::UNITED_STATES_MINOR_OUTLYING_ISLANDS => 'Islas Ultramarinas Menores de Estados Unidos',
            self::URUGUAY => 'Uruguay',
            self::UZBEKISTAN => 'Uzbekistán',
            self::VANUATU => 'Vanuatu',
            self::VENEZUELA => 'Venezuela',
            self::VIET_NAM => 'Vietnam',
            self::VIRGIN_ISLANDS_BRITISH => 'Islas Vírgenes Británicas',
            self::VIRGIN_ISLANDS_US => 'Islas Vírgenes de los Estados Unidos',
            self::WALLIS_AND_FUTUNA => 'Wallis y Futuna',
            self::WESTERN_SAHARA => 'Sahara Occidental',
            self::YEMEN => 'Yemen',
            self::ZAMBIA => 'Zambia',
            self::ZIMBABWE => 'Zimbabue',
            self::UNKNOWN => 'Desconocido',
        };
    }
}
